### ISSUE TITLE
Geospatial_store can not access mongodb remotely

### ISSUE THREAD

**Issue by ferdianjovan** [strands-project/soma#10]
I got an error from geospatial_store which tells me that it can not connect to localhost:62345.

```
[ERROR] [WallTime: 1429726545.957402] Exception in your execute callback: could not connect to localhost:62345: [Errno 111] Connection refused
Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/actionlib/simple_action_server.py", line 299, in executeLoop
    self.execute_callback(goal)
  File "/home/strands/g4s_ws/src/trajectory_behaviours/relational_learner/scripts/OfflineLearning_action.py", line 29, in execute
    if not self.cond(): ol.learn()
  File "/home/strands/g4s_ws/src/trajectory_behaviours/relational_learner/scripts/learn_traj_behaviours.py", line 160, in learn
    r = run_all()
  File "/home/strands/g4s_ws/src/trajectory_behaviours/relational_learner/scripts/learn_traj_behaviours.py", line 58, in run_all
    gs = GeoSpatialStoreProxy('geospatial_store','soma')
  File "/home/strands/g4s_ws/src/soma/soma_geospatial_store/src/soma_geospatial_store/geospatial_store.py", line 43, in __init__
    self._client = pymongo.MongoClient(host,port)
  File "/usr/lib/python2.7/dist-packages/pymongo/mongo_client.py", line 352, in __init__
    raise ConnectionFailure(str(e))
ConnectionFailure: could not connect to localhost:62345: [Errno 111] Connection refused
```

This is wrong since it is supposed to access mongodb in other computer remotely (from bobl to bob).

**Comment by hawesie** [comment]
The soma code is fine. Something is wrong with how we're launching mongodb. 

```
rosparam get mongodb_host
```

Should not return localhost.

**Comment by hawesie** [comment]
https://github.com/strands-project/g4s_deployment/pull/29
